### PR TITLE
Issue 367: Add system to keep citation files in sync with DESCRIPTION

### LINKED ISSUE #367: Set up system to sync `CITATION` and `DESCRIPTION` as well as `citation.cff`.
It would be good to implement the citation syncing system in {EpiNow2} implemented in https://github.com/epiforecasts/EpiNow2/pull/467. 

This would involve:

* regenerating CITATION when relevant fields in DESCRIPTION change,
* generating a `citation.cff` file through a workflow that tracks both CITATION and DESCRIPTION.

I'm happy to submit a PR if you think it's worth implementing here.

### PR DESCRIPTION
**Pull request by jamesmbaazam**
## Description

This PR closes #367. 

In this PR, I set up the `inst/CITATION` file to pull relevant fields from the DESCRIPTION file. I also add a workflow to generate a `citation.cff` whenever relevant fields in CITATION and DESCRIPTION files change. This way, the package always has up-to-date citation information, which can be copied from the citation panel on the package landing page or by running `citation(epinowcast)`. 

## Checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [x] I have read the [contribution guidelines](https://github.com/epinowcast/epinowcast/blob/main/CONTRIBUTING.md).
- [x] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [x] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [x] I have added a news item linked to this PR.
- [x] I have updated the package development version by one increment in both `NEWS.md` and the `DESCRIPTION`.
- [x] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Review by seabbs — CHANGES_REQUESTED** [review]
This looks great James thanks. Could you put a new news item in referring to this PR and also add yourself as a contributor if you are happy to do so?

**Review by seabbs — APPROVED** [review]
Nice this looks great. The only remaining thing to do is to update the README to include this but I think we should do that once its on `main` via the CI workflow vs here.

**Comment by seabbs** [comment]
Are you happy for me to go ahead and merge this @jamesmbaazam?

**Comment by jamesmbaazam** [comment]
Yes,please go ahead.

**Pull request merged**
