### PR TITLE
Use enwtheme

### PR DESCRIPTION
**Pull request by Bisaloo**
## Description

This PR solves https://github.com/epinowcast/epinowcast/pull/410#issuecomment-1853958524.

Preview:

Screen Shot 2023-12-19 at 15 49 59-fullpage

pkgdown theme repo: https://github.com/epinowcast/enwtheme

Next step is probably copying the other theming elements there. I'm just waiting for the confirmation we want these elements to be applied across the org first.

https://github.com/epinowcast/epinowcast/blob/cb8434bf90e42c4739345c778bd53c45ef2ce217/_pkgdown.yml#L3-L5

## Checklist

- [ ] My PR is based on a package issue and I have explicitly linked it.
- [ ] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [ ] I have read the [contribution guidelines](https://github.com/epinowcast/epinowcast/blob/main/CONTRIBUTING.md).
- [ ] I have tested my changes locally.
- [ ] I have added or updated unit tests where necessary.
- [ ] I have updated the documentation if required.
- [ ] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [ ] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by pearsonca** [comment]
The upside of this being that as we release other packages, they should also just use this theme and pretty much problem solved? Nice.

So this goes in before #410, then the changes there have no impact on the pkgdown presentation?

**Comment by Bisaloo** [comment]
> The upside of this being that as we release other packages, they should also just use this theme and pretty much problem solved? Nice.

Yes, exactly.

> So this goes in before https://github.com/epinowcast/epinowcast/pull/410, then the changes there have no impact on the pkgdown presentation?

A minor change: I have added a link to the style guide there, which is not present in the standard pkgdown theme. But it seemed to be a good fit so I put it there. Let me know if I should go back to mimicking the standard pkgdown theme as closely as possible.

> aside: seems weird that this would trigger coverage check + benchmarking, right?

It depends what you mean. This matches with what we put in our GHA workflows so everything is happening as planned. It might not be desirable though and it's possible to update our workflow triggers to only run on relevant changes. 
In my experience however, this can cause more frustration because it means that workflows marked as `required` will not always run, and the PR can only be merged by bypassing the branch protection rules.

**Comment by pearsonca** [comment]
> A minor change: I have added a link to the style guide there, which is not present in the standard pkgdown theme. But it seemed to be a good fit so I put it there. Let me know if I should go back to mimicking the standard pkgdown theme as closely as possible.

I think we should have it - @seabbs?
 
> It depends what you mean. This matches with what we put in our GHA workflows so everything is happening as planned. It might not be desirable though and it's possible to update our workflow triggers to only run on relevant changes. In my experience however, this can cause more frustration because it means that workflows marked as `required` will not always run, and the PR can only be merged by bypassing the branch protection rules.

Hmm. To me, the right solution is a bit more like "workflows trigger -> recognize they have nothing to do -> report as such" - keeps the logic of is-change-relevant-to-workflow closer to the actual knowledge. Is that plausible?

**Comment by seabbs** [comment]
This is great - thanks @Bisaloo. 

> A minor change: I have added a link to the style guide there, which is not present in the standard pkgdown theme. But it seemed to be a good fit so I put it there. Let me know if I should go back to mimicking the standard pkgdown theme as closely as possible.

Yes, I agree this is a good thing to have in. 

>Next step is probably copying the other theming elements there. I'm just waiting for the confirmation we want these elements to be applied across the org first.

Yeah, I think we want all of these org wide?

**Review by seabbs — DISMISSED** [review]
Looks great. Nice one @Bisaloo and @pearsonca!

**Pull request merged**
