### PR TITLE
Do not use else after stop()

### PR DESCRIPTION
**Pull request by Bisaloo**
In the words of Jenny Bryan: "there is no else, there is only if."

https://speakerdeck.com/jennybc/code-smells-and-feels?slide=45

Having `else` after `return()` of `stop()` increases the number of branches in the code, which makes it harder to read. It also translates into a higher cyclomatic complexity.

### CODE REVIEW

**Comment by pearsonca** [comment]
disagree with this notion as a rule of thumb (and apparently, the cyclomatic complexity metric, if it triggers on this sort of thing).

in this *particular* case, i think the `stopifnot` named argument idiom would be better anyway:

```
stopifnot("error1text"=checkcondition, "error2text"=checkcondition, ...)
```

**Comment by Bisaloo** [comment]
I double checked and indeed, it doesn't affect cyclomatic complexity but I still believe this is a good change that makes the code easier to read.

``` r
cyclocomp::cyclocomp(function() {
  if (a) {
    stop("error") 
  } else {
    message("good")
  }
})
#> [1] 2

cyclocomp::cyclocomp(function() {
  if (a) {
    stop("error") 
  }
  message("good")
})
#> [1] 2
```

<sup>Created on 2023-04-12 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by pearsonca** [comment]
For error-checking / messages, i think this generally reads more clearly (comments for emphasis - they're unnecessary imo, especially if this idiom is repeated through a library)
```
stopifnot( # ... we're doing some error checking
  "checking this feature" = ..., # against some logical expression
  ... # repeat for all the desired checks
)
```

**Comment by pearsonca** [comment]
Aside: I am on-board with the don't-if-else-your-errors mentality, just not necessarily the `return()` bit. There are two useful idioms for returns in branching code:

 - pre declare the object to manipulate, make the manipulations in the different branches, return after the branches.
 - have each branch return at its end

I have a slight preference for the first, but its not always practical, nor is it always more readable.

**Comment by pearsonca** [comment]
looking at the linked JB example, agree the LHS is code smell, but again: the `stopifnot(...)` idiom would be a much clearer solution than the RHS. That idiom telegraphs: "Here are all the things we can check up front and immediately exit, for reasons".

However, *sometimes* there's actually some branching logic (e.g. when embracing some polymorphism in function arguments, though yes that too can go overboard), and you can't properly check exit conditions until you've made some progress on evaluating arguments.

**Comment by Bisaloo** [comment]
I agree that `stopifnot()` is easier to understand for simple checking. I can do the change for the case at hand.

**Comment by seabbs** [comment]
Everyone agrees it appears the original is not ideal. 

Choice is between using individual if and stop checks or doing a single `stopifnot`. I don't have a strong preference here. @pearsonca could you draft a suggested version using `stopifnot` so we can compare?

**Comment by pearsonca** [comment]
Have y'all stood up style guidelines or some such? I think the practical solution is roughly:

 - do this PR now (agree, generally better + doesn't make move to stopifnot harder)
 - have those style guidelines in place
 - have a issue(s) => PR(s) exclusively focused on implementing guidance item(s), including this one

**Comment by seabbs** [comment]
> Have y'all stood up style guidelines or some such

There are (in the contributing guide) but they are quite vague.

**Comment by Bisaloo** [comment]
Maintaining a thorough style guide is so much work that I usually try to stick with existing ones, even if I disagree with some of their choices (as long as we still agree on most points obviously).

**Comment by pearsonca** [comment]
> Maintaining a thorough style guide is so much work that I usually try to stick with existing ones, even if I disagree with some of their choices (as long as we still agree on most points obviously).

Doesn't have to be complete (e.g. "the specified lintr config passes" covers a *lot*), and this is more of a "style" guide anyway. I *think* it's roughly at the moment:

 - generally, name exported functions with `enw_...`, and *don't* do that for internal functions
 - do check arguments on externally facing functions, don't on internal ones
 - require `data.frame` only for inputs, indicate `data.table` for outputs
 - (as of this discussion) check as many arguments at the outset of `enw_` with `stopifnot(...)` block

Others?

I do think the contributing guidelines currently are too focused on "process" - worthwhile to establish what is the "vocabulary" or "idioms" for enw. That's has some elements of "style" guidelines, but is generally a bit more meta (i.e. human-enforceable only) than concrete (i.e. static analysis works fine).

**Comment by seabbs** [comment]
> Doesn't have to be complete (e.g. "the specified lintr config passes" covers a lot), and this is more of a "style" guide anyway. I think it's roughly at the moment

These are some good points @pearsonca. Shall we move this discussion to an issue ahead of updating the contributing guide? 

@TimTaylor !!! (all good points)

**Comment by pearsonca** [comment]
In terms of actual code, for `check_date`, I'd prefer something akin to:

```r
with(obs, stopifnot(
  "Both `reference_date` and `report_date` must be columns." =
     !(is.null(reference_date) && is.null(report_date)),
  "`reference_date` must be a column." = !is.null(reference_date),
  "`report_date` must be a column." = !is.null(report_date),
 local = ... # not quite sure here; seems like this is an internal function used for checks - parent.frame?
))
```

probably before the internal copy steps as well?

**Review by seabbs — APPROVED** [review]
LGTM to me. I have added a news item and bumped the dev version. Porting the outstanding conversation here to two new issues.

**Comment by seabbs** [comment]
#233 captures the discussion here on approaches for improving input checking.

**Pull request merged**
