### PR TITLE
Issue 440: restore benchmarks

### LINKED ISSUE #440: Touchstone isn't working
Benchmarking actions have failed recently

### PR DESCRIPTION
**Pull request by sbfnk**
## Description

This PR closes #440.

It does so by changing the action to use the upstream repo.

The `touchstone_ref` argument is needed as by default it'll use outdated `v1` so won't get any emojis.

## Checklist

- [X] My PR is based on a package issue and I have explicitly linked it.
- [X] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [X] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [ ] I have tested my changes locally.
- [ ] I have added or updated unit tests where necessary.
- [ ] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [ ] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by sbfnk** [comment]
I feel the benchmark action should be triggered now that I've updated the path in 5f06b62, not sure why it isn't.

**Comment by sbfnk** [comment]
Not quite sure why the benchmarking action isn't triggered now that I've updated the path in the action.

**Comment by seabbs** [comment]
@sbfnk any idea on a fix here? 

I had to do some more work on this to get it to have `cmdstan` installed and general clean up but now seeing what I think was a problem  we had previously and I thought this update had fixed?

**Comment by sbfnk** [comment]
Thanks for having a look! The issue now seems to be with installing `ggplot2` which may be related to issues we've seen across packages (new version?). I'll try again now just in case it was intermittent.

**Comment by seabbs** [comment]
ah good point (this was making me sad so very glad it was the answer)

**Pull request merged**
