### PR TITLE
Updates citation file with new authors

### LINKED ISSUE #230: Update citation
Since `0.2.0` we have gained new package authors. These need to be added to the `CITATION` file and the README needs to be rendered (using `devtools::build_readme()`) ahead of the release of `0.2.1`.

### PR DESCRIPTION
**Pull request by seabbs**
This PR closes #230 by updating the `CITATION` file with the new package authors and rerendering the `README`.

### CODE REVIEW

**Review by seabbs — COMMENTED** [review]
LGMT (self-review).

**Comment by seabbs** [comment]
😆 sorry that is my bad. I just assumed I couldn't muck this up!

**Comment by seabbs** [comment]
Clearly I could. Will update in another PR (woop woop)

**Comment by seabbs** [comment]
Okay. Do you have an example of this? I am not finding one!

**Comment by Bisaloo** [comment]
https://github.com/r-lib/usethis/issues/1695

**Pull request merged**
