### PR TITLE
DO NOT MERGE: Test PR for issue 385

### PR DESCRIPTION
**Pull request by seabbs**
…d code

 
## Description

Tests #386 using soft depreciated features and an old version of `cmdstan`.

### CODE REVIEW

**Comment by seabbs** [comment]
Hmm @Bisaloo any ideas for getting the action to run? Otherwise just testing using `act` locally.

**Comment by Bisaloo** [comment]
> Hmm @Bisaloo any ideas for getting the action to run? Otherwise just testing using act locally.

Maybe try removing the `branch` condition on your `push` trigger?

**Comment by Bisaloo** [comment]
Could we target `main` to double check `R CMD check` is passing in these cases? Not 100% necessary but curious to confirm

**Comment by seabbs** [comment]
Sigh these are all failing as they target the latest `cmdstan` version. Sigh!

**Comment by seabbs** [comment]
😢 this version doesn't support multi-threading so fails... I think it proves the point though as tests running cmdstanr are only failing due to fitting issues and not due to the soft depreciations.

**Pull request closed without merging**
