### PR TITLE
Issue 457: Standardise function group punctuation

### LINKED ISSUE #457: Inconsistent punctuation in function group descriptions
In the `epinowcast` function reference section, some descriptions have a full stop after them and some don't. For example:

https://github.com/epinowcast/epinowcast/blob/90f7a5a05892a9d176cc71422b796b1c54aa24d6/_pkgdown.yml#L36

https://github.com/epinowcast/epinowcast/blob/90f7a5a05892a9d176cc71422b796b1c54aa24d6/_pkgdown.yml#L40

Suggest being consistent here.

### PR DESCRIPTION
**Pull request by athowes**
## Description

This PR closes #457.

## Checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [x] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [x] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [x] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [x] I have added a news item linked to this PR.
- [x] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Review by seabbs — APPROVED** [review]
This is great thanks! Are you already a contributor on the DESCRIPTION? If not could you add yourself as one if happy to do so as per the contributor guidelines

**Review by seabbs — APPROVED** [review]

**Comment by athowes** [comment]
May have incorrectly done this with Git but should be ok to merge now. (Let me know what I should have done?)

**Comment by seabbs** [comment]
No looks all good I think

**Review by seabbs — APPROVED** [review]

**Comment by seabbs** [comment]
Note I added a news item in #460 which also increments the news to add a development version.

**Pull request merged**
