### PR TITLE
draft change: add_pooling_effect to more generic finder_fn

### PR DESCRIPTION
**Pull request by pearsonca**
still need some other `finder_fn` examples to add to testing?

### CODE REVIEW

**Review by seabbs — CHANGES_REQUESTED** [review]
This all looks good to me and as suggested is certainly clearer. Aside from another test case, which we can sort of dream up I think, it is important we have a really clear news note here indicating that this is a breaking change. I actually wonder if we should have a news section for breaking changes specifically just to highlight this.

**Comment by pearsonca** [comment]
added another test to highlight `...` capability + drafted NEWS update.

also noted during testing that `enw_add_pooling_effect` side effects it's argument. that's not *generally* the approach used elsewhere in the library, but the documentation does (sorta) frame it that way.

**Comment by pearsonca** [comment]
ugh, so this kinda goes beyond the limited scope of the issue, but:
should we address applying the interface ethos (this is public, therefore: should be documented as taking a data.frame, should not side effect argument, etc)?
OR should that be addressed as some comprehensive review targetting only that question => changes (+ writing developer guidance for that)?

**Comment by seabbs** [comment]
I just tweaked the proposed news item and incremented the development version. Just doing a final review and then will merge.

> ugh, so this kinda goes beyond the limited scope of the issue, but:
should we address applying the interface ethos (this is public, therefore: should be documented as taking a data.frame, should not side effect argument, etc)?
OR should that be addressed as some comprehensive review targetting only that question => changes (+ writing developer guidance for that)? (i.e. something addressing https://github.com/epinowcast/epinowcast/issues/211)

I think this goes beyond the scope of this issue and we should deal with it in #211 as you suggest.

**Review by seabbs — APPROVED** [review]
LGTM

**Pull request merged**
