### PR TITLE
depend on coerceDT

### PR DESCRIPTION
**Pull request by pearsonca**
## Description

This PR address elements of #233 by consolidating to depend on `coerceDT` library (still a WIP, hence expecting this PR to be draft for a bit while we work both libraries).

## Checklist

- [X] My PR is based on a package issue and I have explicitly linked it.
- [ ] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [X] I have read the [contribution guidelines](https://github.com/epinowcast/epinowcast/blob/main/CONTRIBUTING.md).
- [ ] I have tested my changes locally.
- [ ] I have added or updated unit tests where necessary.
- [ ] I have updated the documentation if required.
- [ ] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [ ] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by pearsonca** [comment]
Looking at how we use `coerceDT` here and the related functionality in scoringutils, seems like there is appetite for "custom" messages.

I think a good 90-95% solution would be:
 - provide `crc_message` (coerce, for either select or drop warnings), `fbd_message`, and `exp_message` (forbid, expect) arguments
 - those arguments can either be a character string, which will be used as a format string, and passed the offending column names combined as a comma-separated string
 - ... or a function which receives the offending column names and returns a string (future: some of the function-based failing values / other info)

and where the default behavior is set by default values for those arguments.

@seabbs / @nikosbosse - thoughts?

**Comment by pearsonca** [comment]
There are two epinowcast-specific items that don't really generalize (to coerceDT package): dates + group.

Propose:
 - for dates, have an epinowcast package option for required date column names, use that as an addition to the select (this may also require a new feature for coerceDT - a "." select support
 - for group, re-introduce a check_group function

**Comment by pearsonca** [comment]
> There are two epinowcast-specific items that don't really generalize (to coerceDT package): dates + group.
> 
> Propose:
> 
> * for dates, have an epinowcast package option for required date column names, use that as an addition to the select (this may also require a new feature for coerceDT - a "." select support
> * for group, re-introduce a check_group function

Alternative-and-actually-general approach for `.group` - offer a `coalesce` argument on coerceDT (and therefore makeDT). Meaning "`select` this column if present, otherwise use this default value"

**Comment by seabbs** [comment]
This all sounds and looks good but going to close until we have a version that is ready to PR in!

**Pull request closed without merging**
