### PR TITLE
Issue 331: Add partial matching & global state checks in testthat checks

### LINKED ISSUE #331: Add partial argument warning to testing
Add a test to check functions fully use their argument names in `testthat`. See https://github.com/epiforecasts/EpiNow2/issues/473#issuecomment-1761412120

### PR DESCRIPTION
**Pull request by Bisaloo**
## Description

This PR closes #331.

I believe these two changes are small enough to be a single PR and I have ensured they are done in distinct commits. But please let me know if you'd prefer I open two PR.

## Checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [x] I have read the [contribution guidelines](https://github.com/epinowcast/epinowcast/blob/main/CONTRIBUTING.md).
- [x] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [x] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [x] I have added a news item linked to this PR.
- [ ] I have updated the package development version by one increment in both `NEWS.md` and the `DESCRIPTION`.
- [ ] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by seabbs** [comment]
Thanks @Bisaloo! 

Note the CI failure here is due to https://github.com/epinowcast/epinowcast/issues/339 rather than anything in this PR.

**Review by seabbs — APPROVED** [review]
This is great. Thanks 😍

**Comment by Bisaloo** [comment]
I just realized I committed an empty file for `setup-options.R`. Not sure how I managed that but let me create a follow up PR. My apologies :cry:

**Comment by seabbs** [comment]
ah sorry I saw this and assumed it was related to the setup of the new state change watcher but obviously that makes no sense! That would be great - thanks.

**Pull request merged**
